
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: food_train_development

test:
  <<: *default
  database: food_train_test

production:
  <<: *default
  database: food_train_production
  username: food_train
  password: <%= ENV['FOOD_TRAIN_DATABASE_PASSWORD'] %>
